version: '3.8'

services:
  api:
    container_name: json-keeper-api
    restart: always
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - mocker-network
  database:
    image: postgres
    container_name: json-keeper-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsonkeeper
    ports:
      - "5432:5432"
    volumes:
      - /:/data/postgres
    networks:
      - mocker-network

networks:
  mocker-network:
    driver: bridge
